my_data=read.csv(file.choose()) .  # uploading the file in the console
dim(my_state)
dim(my_data) #dim is used to give dimensions for the data set 
head[,12]
my_data[,12]
names(my_data)
my_data$Floor
barplot(my_data$Floor)#bar diagram
barplot((my_data$Floor)/length(my_data$Floor))
table(my_data$Floor)
barplot(table(my_data$Floor))
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1")
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim="50")
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim=50)
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim = [,50])
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim =c(0,50))
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim =c(0,40))
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim =c(0,40),xlim=c(0,30))           
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim =c(0,40))
barplot(table(my_data$Floor),main="Apartment availability for each category of room",xlab="Number of Rooms",ylab="Number of Apartments",col="indianred1",ylim =c(0,40))
names(my_data)
install.packages("plotrix")
library(plotrix)
pie3D(my_data$Type)
table(my_data$Type)
pie3D(table(my_data$Type))
pie3D(table(my_data$Type),main="Type of Property",explode=0.2)
pie3D(table(my_data$Type),main="Type of Property",explode=0.2,col=c(coral,lightcoral))
pie3D(table(my_data$Type),main="Type of Property",col=c(coral,lightcoral))
pie3D(table(my_data$Type),main="Type of Property",col="lightpink")
pie3D(table(my_data$Type),main="Type of Property",col=c("lightpink","coral"))
pie3D(table(my_data$Type),main="Type of Property",col=c("lightpink","coral"),explode=0.2)
labels=c("Residential","Commercial")
pie3D(table(my_data$Type),labels,main="Type of Property",col=c("orchid","powderblue"),explode=0.2)
v=c(160,15)
pie3D(v,labels,main="Type of Property",col=c("orchid","powderblue"),explode=0.2)
labela=c("Commercial","Residential")
pct=round(v/sum(v)*100)
lbls=paste(labela,pct)
lbls=paste(lbls,"%",sep="")
pie3D(v,labela=lbls,explode=0.2,main="Type of Property")
labels=c("Commercial","Residential")
pct=round(v/sum(v)*100)
lbls=paste(labela,pct)
lbls=paste(lbls,"%",sep="")
pie3D(v,labels=lbls,explode=0.2,main="Type of Property")
pie3D(v,labels=lbls,explode=0.2,main="Type of Property",col=c("stateblue1","tomato"))
pie3D(v,labels=lbls,explode=0.2,main="Type of Property",col=c("stateblue1","tomato"))
pct=round(v/sum(v)*100)
lbls=paste
lbls=paste(lbls,"%",sep="")
pie3D(v,labels=lbls,explode=0.5,main="Type of Property",col=c("royalblue","tomato"))
pie3D(v,labels=lbls,explode=0.7,main="Type of Property",col=c("royalblue","tomato"))
pie3D(v,labels=lbls,explode=1.0,main="Type of Property",col=c("royalblue","tomato"))
pie3D(v,labels=lbls,explode=0.5,main="Type of Property",col=c("royalblue","tomato"))
names(my_data)
my_data$RENT.INR
range(my_data$RENT.INR)
hist(my_data$RENT.INR)
table(my_data$RENT.INR)
d=density(my_data$RENT.INR)
plot(d,main="Rent")
polygon(d,col="red",border="blue")
barplot(my_data$RENT.INR)
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red")
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlin=c(0,450000))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlim=c(0,450000))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlim=c(0,450000),ylin=c(0,200))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red")
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlab="Rent in INR",ylab="Number of Apartments")
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,500000))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,500000),ylim=c(0,200))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="red",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000),border="blue")
barplot(my_data$RENT.INR,main="Rent of the apartments",col="slateblue4",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="palevioletred1",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000))
attach(my_data$RENT.INR)
library("scatterplot3d")
install.packages("scatterplt3d")
install.packages("scatterplot3d")
library(scatterplort3d)
library(scatterplot3d)
attach(my_data$RENT.INR)
barplot(my_data$RENT.INR,main="Rent of the apartments",col="palevioletred1",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000),xfitseq(min(x),max(x),length=180))
barplot(my_data$RENT.INR,main="Rent of the apartments",col="palevioletred1",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000),horiz = TRUE)
barplot(my_data$RENT.INR,main="Rent of the apartments",col="palevioletred1",xlab="Rent in INR",ylab="Number of Apartments",xlim=c(0,200),ylim=c(0,500000))
names(my_data)
(my_data$RENT.INR)
range(my_data$RENT.INR)
breaks=seq(15000,450000,by=50000)
breaks
(my_data$RENT.INR).cut=cut((my_data$RENT.INR),breaks,right=FALSE)
((my_data$RENT.INR).cut)=cut((my_data$RENT.INR),breaks,right=FALSE)
((my_data$RENT.INR).cut)=(cut((my_data$RENT.INR),breaks,right=FALSE))
my_data$RENT.INR.cut=cut(my_data$RENT.INR,breaks,right=FALSE)
my_data$RENT.INR.cut
table(my_data$RENT.INR.cut)
barplot(table(my_data$RENT.INR.cut))
breaks=seq(15000,450000,by=25000)
breaks
(my_data$RENT.INR).cut=cut((my_data$RENT.INR),breaks,right=FALSE)
my_data$RENT.INR.cut=cut(my_data$RENT.INR,breaks,right=FALSE)
my_data$RENT.INR.cut
table(my_data$RENT.INR.cut)
hist(table(my_data$RENT.INR.cut))
my=c(my_data$RENT.INR)*12
my
range(my)
breaks=seq(180000,5200000,by=10000)#seq
breaks
my.cut=cut(my,breaks,right=FALSE)
my.cut=cut(my,breaks,right=FALSE)
my.cut
table(my.cut)
my.cut
table(my.cut)
barplot(table(my.cut))
hist(table(my.cut))
breaks=seq(0,250000,by=10000)
breaks
my.cut=cut(my,breaks,right=FALSE)
my.cut
table(my.cut)
barplot(table(my.cut))
hist(table(my.cut))
count(table(my.cut))
sum(table(my.cut))
notax=sum(table(my.cut))
breaks=seq(250000,50000,by=10000)
breaks=seq(250000,500000,by=10000)
breaks
my.cut=cut(my,breaks,right=FALSE)
my.cut
table(my.cut)
sum(table(my.cut))
smalltax=sum(table(my.cut))
breaks=seq(500000,1000000,by=10000)
breaks
my.cut=cut(my,breaks,right=FALSE)
my.cut
table(my.cut)
sum(table(my.cut))
mediumtax=sum(table(my.cut))
range(my)
breaks=seq(500000,10000000,by=10000)
range(my)
breaks=seq(500000,10000000,by=10000)
breaks
my.cut=cut(my,breaks,right=FALSE)
my.cut
table(my.cut)
sum=table(my.cut)
sum(table(my.cut))
hightax=sum(table(my.cut))
taxation=c(notax,smalltax,mediumtax,hightax)
table(taxation)
hist(taxation)
barplot(taxation)
b=c("No Tax (Below 2.5L"),"5% Tax (5L-10L)","20% Tax(10L-20L)","30% Tax (10L+)")
b=c("No Tax (Below 2.5L)","5% Tax (5L-10L)","20% Tax(10L-20L)","30% Tax (10L+)")
barplot(taxation,names.arg=b,xlab="Income from Rent")
hist(taxation,names.arg=b,xlab="Income from Rent")
pie(taxation,names.arg=b,xlab="Income from Rent")
barplot(taxation,names.arg=b,xlab="Income from Rent")
b=c("No Tax (<2.5L)","5% Tax (5L-10L)","20% Tax(10L-20L)","30% Tax (10L<)")
barplot(taxation,names.arg=b,xlab="Income from Rent")
b=c("No Tax(<2.5L)","5% Tax(5L-10L)","20%Tax(10L-20L)","30% Tax(10L<)")
barplot(taxation,names.arg=b,xlab="Income from Rent")
barplot(taxation,names.arg=b,xlab="Income from Rent",col="red")
barplot(taxation,names.arg=b,xlab="Income from Rent",ylab="Number of People")
b=c("No Tax","5% Tax","20%Tax","30% Tax(10L<)")
b=c("No Tax","5% Tax","20% Tax","30% Tax")
barplot(taxation,names.arg=b,xlab="Income from Rent",ylab="Number of People")
barplot(taxation,names.arg=b,xlab="Income from Rent",ylab="Number of People",main="Taxation",col=c("olivedrab1","darkorange","red","red4"))
barplot(taxation,names.arg=b,xlab="Income from Rent",ylab="Number of People",main="Taxation",col=c("khaki","darkorange","red","red4"))
barplot(taxation,names.arg=b,xlab="Income from Rent",ylab="Number of People",main="Taxation",col=c("olivedrab1","khaki","red","red4"))
my_data=read.csv(file.choose())
dim(my_data)
my_data$AREA
table(my_data$AREA)
my_rental=read.csv(file.choose())
my_rental$AREA
table9my_rental$AREA
table(my_rental$AREA)
pie3D(table(my_rental$AREA))
and=4
bkc=11
bandstand=20
bha=7
church=18
churche=29
churchw=60
colaba=8
jvp=8
jw=7
saki=1
barplot(table(my_rental$AREA))
bandra=(bandstand+bha)
bandra
churchgate=church+churche+churchw
churchgate
juhu=jvp+jw
juhu
d=density(table(my_rental$AREA))
plot(d)
ciy=(and+bkc+bandstand+bha+church+churche+churchw+colaba+jvp+jw+saki)
d=density(city)
d=density(table(my_rental$AREA))
plot(d,main="Kernel Density of Population")
polygon(d,col="cornflowerblue")
polygon(d,col="cornflowerblue",ylab="Location")
plot(d,main="Kernel Density of Poulation",ylab="Location")
plot(d,main="Kernel Density of Poulation",xlab="Location",col="cornflowerblue")
polygon(d,col="cornflowerblue")
counts=(bkc,bandstand)
counts=table(bkc,bandstand)
barplot(counts)
(table(my_rental$AREA))
barplot(table(my_rental$AREA))
area=c(and,bkc,bandstand,bha,church,churche,churchw,colaba,jvp,jw,saki)
table(area)
barplot(table(area))
pie(table(my_rental$AREA))
pie(table(area))
sum(my_rental$AREA)
l=table(area)
(my_rental$AREA)
table(my_rental$AREA)
x=table(my_rental$AREA)
labels=c("Andheri","Bandra-BKC","Bandra Band Stand","Bhyander","Churchgate-C","Churchgate-E","Churchgate-W","Colaba","Juhu-VP","Juhu-W","Sakinaka")
pct=round(x/sum(x)*100)
lbls=paste(labels,pct)
lbls=paste(lbls,"%",sep"")
lbls=paste(lbls,"%",sep="")
pie3D(x,labels=lbls)
pie3D(x,labels=lbls,explode=0.8)
pie3D(x,labels=lbls,explode=0.8,minangle=0.5)
pie3D(x,labels=lbls,explode=0.8,labelpos = 1p)
pie3D(x,labels=lbls,explode=0.8,radius=0.5)
pie3D(x,labels=lbls,explode=0.8,radius=5.0)
pie3D(x,labels=lbls,explode=0.8,radius=2.0)
pie3D(x,labels=lbls,explode=2.0,rpie3D(x,labels=lbls,explode=0.8,minsep=2.0)adius=2.0)
help("pie3D.labels")
library(plotrix)#library 
pie3D.labels (labels=lbls,minsep=2.0,labelrad=0.1)
names(my_rental)
plot(my_rental$AREA,my_rental$RENT_INR)
plot(my_rental$AREA,my_rental$RENT_INR,pch=19)
plot(my_rental$AREA,my_rental$RENT_INR,pch=19,xlab="Area")
scatter.smooth(my_rental$AREA,my_rental$RENT_INR)
library(hexbin)
install.packages("hexbin")
library(hexbin)
bin=(my_rental$AREA,my_rental$RENT_INR)
bin=hexbin(my_rental$AREA,my_rental$RENT_INR)
plot(bin)
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=50)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=1000)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=800)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=500)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=300)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=010)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=050)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent")
bin=hexbin(table(my_rental$AREA),my_rental$RENT_INR,xbins=050)
bin=hexbin(table(my_rental$AREA),tabe(my_rental$RENT_INR),xbins=050)
bin=hexbin(table(my_rental$AREA),table(my_rental$RENT_INR),xbins=050)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",style="nested.lattice")
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY)
bin=hexbin(my_rental$AREA,my_rental$RENT_INR,xbins=050)#bin
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=1.2)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=2.0)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=2.5)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=3.5)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=3.0)
plot(bin,main="Area wise demand",xlab="AREA",ylab="Rent",colramp=BTY,legend=2.0)
